### ISSUE TITLE
Main plot fails

### ISSUE THREAD

**Issue by dhvalden** [RobustiPy/robustipy#19]
Main plot fails to be produce.

Steps to reproduce:
1- create a new directory and install robustipy from pypi.
2- copy data from old directory of union example (data not shared yet in pypi for data privacy reasons)
3- Copy replication_example.py in new directory (not distributed yet, as data not shared yet).
4- run example only with union data.

**Comment by dhvalden** [comment]
`/home/daniel/code/test/lib64/python3.12/site-packages/robustipy/figures.py:334: UserWarning: Dataset has 0 variance; skipping density estimate. Pass `warn_singular=False` to disable this warning.
  sns.kdeplot(results_object.summary_df['av_k_metric'], ax=ax,
Traceback (most recent call last):
  File "/home/daniel/code/test/replication_example.py", line 24, in <module>
    union_example()
  File "/home/daniel/code/test/replication_example.py", line 14, in union_example
    union_results.plot(specs=[['hours', 'collgrad'],
  File "/home/daniel/code/test/lib64/python3.12/site-packages/robustipy/models.py", line 266, in plot
    return plot_results(results_object=self,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/code/test/lib64/python3.12/site-packages/robustipy/figures.py", line 454, in plot_results
    plot_kfolds(results_object, ax5)
  File "/home/daniel/code/test/lib64/python3.12/site-packages/robustipy/figures.py", line 336, in plot_kfolds
    sns.histplot(results_object.summary_df['av_k_metric'], ax=ax,
  File "/home/daniel/code/test/lib64/python3.12/site-packages/seaborn/distributions.py", line 1416, in histplot
    p.plot_univariate_histogram(
  File "/home/daniel/code/test/lib64/python3.12/site-packages/seaborn/distributions.py", line 470, in plot_univariate_histogram
    bin_kws = estimator._define_bin_params(sub_data, orient, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/code/test/lib64/python3.12/site-packages/seaborn/_stats/counting.py", line 152, in _define_bin_params
    bin_edges = self._define_bin_edges(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/code/test/lib64/python3.12/site-packages/seaborn/_stats/counting.py", line 133, in _define_bin_edges
    bin_edges = np.arange(start - .5, stop + 1.5)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: arange: cannot compute length
`

**Comment by vallerrr** [comment]
@dhvalden This might be solved by setting the kfold = 5. please try this, thanks!

**Comment by dhvalden** [comment]
Solved in https://github.com/RobustiPy/robustipy/commit/84096faa2e15f5621fa5b8099d194f6ccfa367d5
